### ISSUE TITLE
SysDig Operator does not seem to set appropriate SCC on OpenShift

### ISSUE THREAD

**Issue by kitch** [sysdiglabs/sysdig-operator#1]
On OpenShift the SysDig agent needs additional Security Context Constraints enabled. Namely that it needs to have privileged SCC add. Likely need to add this step to the operator.

```
oc adm policy add-scc-to-user privileged -n <namespace> -z <service account>
```

**Comment by bencer** [comment]
Hi @kitch , @sbarre-esit ,

the issue here is that because the operator is based on the Helm chart cannot create the add-scc-to-user privileged policy on OpenShift out of the box.

The steps to get this installed on OpenShift would be creating the account first and the policy manually:

`
$ oc new-project sysdig-operator
`
`
$ oc create serviceaccount sysdig-operator
serviceaccount/sysdig-operator created
`
`
$ oc adm policy add-cluster-role-to-user cluster-admin -z sysdig-operator
cluster role "cluster-admin" added: "sysdig-operator"
`

Remove these from the bundle.yaml file (lines 22 to 39) and then apply it:

`
$ oc apply -f bundle.yaml
`

I'm going to keep this issue open until we fix the documentation for the operator or we move into the operator framework that could address this issue.

**Comment by nestorsalceda** [comment]
This has been fixed in latest version :)
